### ISSUE TITLE
Unable To Open XAPK Files

### ISSUE THREAD

**Issue by HonestAbe7** [cloneconf/Apkpurer#1]
I tried to download an app and it was an .XAPK file and was unable to open it.

**Comment by cloneconf** [comment]
You should extract it using something like
 (ZArchiver)[https://play.google.com/store/apps/details?id=ru.zdevs.zarchiver]

**Comment by sunilpaulmathew** [comment]
@cloneconf 
I really don't have expertise in Kotlin, so may not directly contribute. However, if you're interested, you can refer my [Package Manager](https://github.com/SmartPack/PackageManager) app (which also uses code from SAI). The installer related code is available [here](https://github.com/sunilpaulmathew/sCommon/blob/master/library/src/main/java/in/sunilpaulmathew/sCommon/Utils/sInstallerUtils.java) (I recently made it as a library). If you can, code a file picker capable to pick multiple files so that the users can pick only necessary files.
Btw, thanks for this nice app.

**Comment by cloneconf** [comment]
@sunilpaulmathew 
Thanks for the suggestion :)

> I really don't have expertise in Kotlin

Me too man :|
(ok i have but not that much)


> so may not directly contribute

You can contribute in Java, since both Java and Kotlin can work together seamlessly.


> However, if you're interested,

I am not :/
Since i wasn't planing to make it full-feature.
It was just to test what i have learned.


> you can refer my Package Manager app (which also uses code from SAI)

I see, you are really good in these stuff. But unfortunately i am not :-)


> If you can, code a file picker capable to pick multiple files so that the users can pick only necessary files.

I don't know : /



> Btw, thanks for this nice app.

Really appreciated it.
And thanks for your great contributions for the community too ;)

Please don't take it personally, i am just not interested in this app anymore...

Best Regards.
Clone Conflict.
